# Generated by Django 3.2.5 on 2021-07-28 18:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='statusProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomStatus', models.CharField(max_length=20)),
                ('descriptionStatus', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='typeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomType', models.CharField(max_length=50)),
                ('descriptionType', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='usercontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameContact', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('msn', models.TextField(max_length=400)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='newProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho', models.IntegerField()),
                ('largo', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img_productos')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.statusproduct')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typeproduct')),
            ],
        ),
    ]
