# Generated by Django 3.2.5 on 2021-07-31 21:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('comentario', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomGender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomRegion', models.CharField(max_length=50)),
                ('fkPais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('nro_contacto', models.IntegerField()),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('imagen_link', models.TextField(blank=True, max_length=1000)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img_pedido')),
                ('ancho', models.IntegerField()),
                ('largo', models.IntegerField()),
                ('fkAdress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adress')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typeproduct')),
            ],
        ),
        migrations.CreateModel(
            name='extraDataUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsp', models.IntegerField(blank=True)),
                ('birthday', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('instagram', models.CharField(blank=True, max_length=30)),
                ('genderuser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.gender')),
            ],
        ),
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomComuna', models.CharField(max_length=50)),
                ('fkRegion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
            ],
        ),
        migrations.AddField(
            model_name='adress',
            name='fkComuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna'),
        ),
    ]
