# Generated by Django 3.2.5 on 2021-08-01 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210731_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='extradatauser',
            name='comunaUser',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='core.comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extradatauser',
            name='userid',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
