# Generated by Django 3.2.5 on 2021-08-02 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210801_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fkAdress',
        ),
        migrations.AddField(
            model_name='order',
            name='calle',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='comentario',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='fkComuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='adress',
        ),
    ]
