# Generated by Django 3.2.5 on 2021-08-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210801_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='sizeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
