# Generated by Django 3.2.5 on 2021-08-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210803_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeproduct',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sizeproduct',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
