# Generated by Django 3.2.5 on 2021-08-03 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210803_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('comentario', models.CharField(blank=True, max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
                ('nro_contacto', models.IntegerField()),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('imagen_link', models.TextField(blank=True, max_length=1000)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img_pedido')),
                ('fkComuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sizeproduct')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.statusproduct')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typeproduct')),
            ],
        ),
    ]
