# Generated by Django 3.2.5 on 2021-08-03 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_othersize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.sizeproduct'),
        ),
    ]
