# Generated by Django 3.2.5 on 2021-08-03 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_order_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default='CONFIRMADO', on_delete=django.db.models.deletion.CASCADE, to='core.statusproduct'),
        ),
    ]
