# Generated by Django 3.2.5 on 2021-08-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusproduct',
            name='descriptionStatus',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='statusproduct',
            name='nomStatus',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
